#!/usr/bin/env python3
"""Generate, run, collect, and plot sanity-check parameter sweeps.

This script is intentionally a wrapper around
AutoscalerFaasScalarVectorial/simulate.py. It writes input JSON and DAG JSON
files in the shape that simulate.py already expects, then reads the simulator's
existing CSV/JSON outputs. simulate.py is not imported or modified.
"""

from __future__ import annotations

import argparse
import copy
import itertools
import json
import os
import subprocess
import sys
from pathlib import Path
from typing import Any

os.environ.setdefault("MPLCONFIGDIR", "/tmp/matplotlib")

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from mpl_toolkits.mplot3d import Axes3D  # noqa: F401


ROOT = Path(__file__).resolve().parent
PYTHON = ROOT / ".venv" / "bin" / "python"
SIMULATE = ROOT / "AutoscalerFaasScalarVectorial" / "simulate.py"


# ---------------------------------------------------------------------------
# Editable defaults
# ---------------------------------------------------------------------------

# Every key here is consumed by simulate.py's graph experiment path, either
# directly or through GraphServerlessSimulator._build_algo_params().
BASE_SIMULATION_CONFIG: dict[str, Any] = {
    "description": "Sanity-check sweep generated by run_sanitycheck_suite_v2.py",
    "experiment_name": "sanitycheck_sweep",
    "arrival_rate": 10,
    "optimization": {"type": "sgd"},
    "theta": [[1 / 3, 1 / 3, 30]],
    "tau": 100,
    "max_concurrency": 50,
    "max_time": 200000,
    "log_dir": "sanitycheck_sweep/logs",
    "K": 2,
    "seeds": [1],
    "k_delta": 1,
    "k_gamma": [1, 1, 1],
    "k_gamma_per_theta": None,
    "prtb": [[-0.5, 0.5], [-0.5, 0.5], [-1, 1]],
    "learn_mask": [True, True, True],
    "accumulate_cost": True,
    "K_exp": 1000,
    "gamma_min": 1,
    "theta_stock_min": 0,
    "theta_idle_min": 0,
    "stop_by_simulated_time": False,
    "max_simulated_time": 500,
    "exp_per_run": 1,
}

# These node values are single-node target rates by default. With
# scale_node_rates_by_N=True, each per-node rate is multiplied by N, matching
# the old sanity script's convention that serial chain means stay comparable.
NODE_DEFAULTS: dict[str, Any] = {
    "warm_service": {"rate": 0.5, "type": "Exponential"},
    "cold_service": {"rate": 100.0, "type": "Exponential"},
    "cold_start": {"rate": 0.1, "type": "Exponential"},
    "expiration": {"rate": 0.01, "type": "Exponential"},
    "scale_node_rates_by_N": True,
}

# Sweep values may be lists or scalars. N_values and arrival_rate_values are
# the preferred names for node count and external arrival rate. Additional
# supported keys are listed in SWEEP_ALIASES below.
SWEEPS: dict[str, Any] = {
    "N_values": [1,3,5],
    "arrival_rate_values": [10,20],
    "warm_service_values": [0.5,0.3],
    "optimization_values": ["sgd"],
}

# Friendly aliases are accepted here; they are resolved against the actual
# graph-level columns emitted by simulate.py's all_runs_metrics.csv.
Z_METRICS = [
    "response_time",
    "rejection_probability",
    "average_cost",
]

# None means: plot against every non-N input parameter whose sweep has multiple
# values. You may set this to e.g. ["arrival_rate", "warm_service", "optimization"].
PLOT_BY_PARAMETERS: list[str] | None = None


SWEEP_ALIASES = {
    "N_values": "N",
    "nodes_values": "N",
    "arrival_rate_values": "arrival_rate",
    "warm_service_values": "warm_service",
    "warm_service_rate_values": "warm_service",
    "warm_service_mean_values": "warm_service_mean",
    "cold_service_values": "cold_service",
    "cold_service_rate_values": "cold_service",
    "cold_service_mean_values": "cold_service_mean",
    "cold_start_values": "cold_start",
    "cold_start_rate_values": "cold_start",
    "cold_start_mean_values": "cold_start_mean",
    "expiration_values": "expiration",
    "expiration_rate_values": "expiration",
    "expiration_mean_values": "expiration_mean",
    "optimization_values": "optimization",
    "theta_values": "theta",
    "tau_values": "tau",
    "max_concurrency_values": "max_concurrency",
    "max_time_values": "max_time",
    "K_values": "K",
    "seeds_values": "seeds",
    "k_delta_values": "k_delta",
    "k_gamma_values": "k_gamma",
    "k_gamma_per_theta_values": "k_gamma_per_theta",
    "prtb_values": "prtb",
    "learn_mask_values": "learn_mask",
    "accumulate_cost_values": "accumulate_cost",
    "K_exp_values": "K_exp",
    "gamma_min_values": "gamma_min",
    "theta_stock_min_values": "theta_stock_min",
    "theta_idle_min_values": "theta_idle_min",
    "stop_by_simulated_time_values": "stop_by_simulated_time",
    "max_simulated_time_values": "max_simulated_time",
    "exp_per_run_values": "exp_per_run",
}

CONFIG_PARAM_NAMES = {
    "arrival_rate",
    "theta",
    "tau",
    "max_concurrency",
    "max_time",
    "K",
    "seeds",
    "k_delta",
    "k_gamma",
    "k_gamma_per_theta",
    "prtb",
    "learn_mask",
    "accumulate_cost",
    "K_exp",
    "gamma_min",
    "theta_stock_min",
    "theta_idle_min",
    "stop_by_simulated_time",
    "max_simulated_time",
    "exp_per_run",
}

NODE_RATE_PARAMS = {
    "warm_service": "warm_service",
    "cold_service": "cold_service",
    "cold_start": "cold_start",
    "expiration": "expiration",
}

NODE_MEAN_PARAMS = {
    "warm_service_mean": "warm_service",
    "cold_service_mean": "cold_service",
    "cold_start_mean": "cold_start",
    "expiration_mean": "expiration",
}

METRIC_ALIASES = {
    "response_time": ["response_time_avg", "graph_response_time_avg"],
    "average_response_time": ["response_time_avg", "graph_response_time_avg"],
    "rejection_probability": ["prob_reject", "graph_prob_reject"],
    "cold_start_probability": ["prob_cold", "graph_prob_cold"],
    "queued_probability": ["prob_queued", "graph_prob_queued"],
    "warm_probability": ["prob_warm", "graph_prob_warm"],
    "average_cost": ["graph_time_avg_cost", "graph_event_avg_cost"],
    "time_average_cost": ["graph_time_avg_cost"],
    "event_average_cost": ["graph_event_avg_cost"],
}

METADATA_COLUMNS = {
    "status",
    "error",
    "experiment_id",
    "experiment_name",
    "config_path",
    "dag_path",
    "run_dir",
    "stdout_log",
    "N",
    "graph",
}


# ---------------------------------------------------------------------------
# Configuration generation
# ---------------------------------------------------------------------------


def output_root(output_prefix: str) -> Path:
    path = Path(output_prefix)
    return path if path.is_absolute() else ROOT / path


def deep_update(base: dict[str, Any], override: dict[str, Any]) -> dict[str, Any]:
    result = copy.deepcopy(base)
    for key, value in override.items():
        if isinstance(value, dict) and isinstance(result.get(key), dict):
            result[key] = deep_update(result[key], value)
        else:
            result[key] = copy.deepcopy(value)
    return result


def load_runner_config(path: Path | None) -> dict[str, Any]:
    if path is None:
        return {}
    with path.open() as f:
        return json.load(f)


def scalar_or_list(value: Any) -> list[Any]:
    if value is None:
        return [None]
    return value if isinstance(value, list) else [value]


def normalize_sweeps(raw_sweeps: dict[str, Any]) -> dict[str, list[Any]]:
    normalized: dict[str, list[Any]] = {}
    for raw_name, raw_values in raw_sweeps.items():
        name = SWEEP_ALIASES.get(raw_name, raw_name)
        values = scalar_or_list(raw_values)
        if not values:
            continue
        normalized[name] = values
    if "N" not in normalized:
        normalized["N"] = [3]
    return normalized


def cartesian_product(sweeps: dict[str, list[Any]]) -> list[dict[str, Any]]:
    keys = list(sweeps)
    return [dict(zip(keys, values)) for values in itertools.product(*(sweeps[k] for k in keys))]


def chain_label(n_nodes: int) -> str:
    return "A1" if n_nodes == 1 else "->".join(f"A{i}" for i in range(1, n_nodes + 1))


def build_dag(n_nodes: int) -> dict[str, Any]:
    dag = {}
    for idx in range(1, n_nodes + 1):
        node = f"A{idx}"
        dag[node] = {
            "next": [f"A{idx + 1}"] if idx < n_nodes else [],
            "transition_probability": [1.0] if idx < n_nodes else [],
        }
    return {"DirectedAcyclicGraph": dag}


def rate_from_mean(mean: Any) -> float:
    mean_float = float(mean)
    if mean_float <= 0:
        raise ValueError(f"Mean service time must be positive, got {mean}")
    return 1.0 / mean_float


def configured_rate(base_rate: Any, n_nodes: int, scale_by_n: bool) -> float:
    rate = float(base_rate)
    return rate * n_nodes if scale_by_n else rate


def build_nodes(n_nodes: int, node_defaults: dict[str, Any], combo: dict[str, Any]) -> dict[str, Any]:
    scale_by_n = bool(node_defaults.get("scale_node_rates_by_N", True))
    template = {
        key: copy.deepcopy(value)
        for key, value in node_defaults.items()
        if key != "scale_node_rates_by_N"
    }

    for param, distribution in NODE_RATE_PARAMS.items():
        if param in combo and combo[param] is not None:
            template[distribution]["rate"] = combo[param]

    for param, distribution in NODE_MEAN_PARAMS.items():
        if param in combo and combo[param] is not None:
            template[distribution]["rate"] = rate_from_mean(combo[param])

    nodes = {}
    for idx in range(1, n_nodes + 1):
        node = copy.deepcopy(template)
        for distribution in NODE_RATE_PARAMS.values():
            node[distribution]["rate"] = configured_rate(
                node[distribution]["rate"],
                n_nodes,
                scale_by_n,
            )
        nodes[f"A{idx}"] = node
    return nodes


def compact_value(value: Any) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (list, tuple)):
        return "-".join(compact_value(item) for item in value)
    if isinstance(value, dict):
        return "-".join(f"{key}-{compact_value(value[key])}" for key in sorted(value))
    text = str(value)
    return (
        text.replace("/", "_")
        .replace("\\", "_")
        .replace(" ", "")
        .replace(".", "p")
        .replace("-", "m")
        .replace("[", "")
        .replace("]", "")
        .replace(",", "-")
    )


def combo_slug(combo: dict[str, Any]) -> str:
    parts = [f"{key}-{compact_value(combo[key])}" for key in sorted(combo)]
    return "__".join(parts)


def apply_combo_to_config(
    base_config: dict[str, Any],
    node_defaults: dict[str, Any],
    combo: dict[str, Any],
    output_dir: Path,
) -> dict[str, Any]:
    n_nodes = int(combo["N"])
    config = copy.deepcopy(base_config)
    config["arrival_rate"] = combo.get("arrival_rate", config["arrival_rate"])
    config["nodes"] = build_nodes(n_nodes, node_defaults, combo)
    config["log_dir"] = str(output_dir / "logs")
    config["description"] = f"{config.get('description', '').strip()} | {combo_slug(combo)}"
    config["experiment_name"] = f"{config.get('experiment_name', 'sanitycheck')}_{combo_slug(combo)}"

    if "optimization" in combo:
        config["optimization"] = (
            combo["optimization"]
            if isinstance(combo["optimization"], dict)
            else {"type": combo["optimization"]}
        )

    for param in CONFIG_PARAM_NAMES:
        if param not in combo or combo[param] is None:
            continue
        config[param] = combo[param]

    # simulate.py expects absent optional keys to fall back to defaults. Dropping
    # None keeps the generated JSON cleaner and avoids accidental null handling.
    return {key: value for key, value in config.items() if value is not None}


def write_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w") as f:
        json.dump(payload, f, indent=2)
        f.write("\n")


def generate_experiment_files(
    combos: list[dict[str, Any]],
    base_config: dict[str, Any],
    node_defaults: dict[str, Any],
    output_dir: Path,
) -> list[dict[str, Any]]:
    generated = []
    for combo in combos:
        n_nodes = int(combo["N"])
        experiment_id = combo_slug(combo)
        config_dir = output_dir / "configs" / experiment_id
        dag_path = config_dir / f"DAG_N{n_nodes:02d}.json"
        input_path = config_dir / f"input_N{n_nodes:02d}.json"
        config = apply_combo_to_config(base_config, node_defaults, combo, output_dir)
        write_json(dag_path, build_dag(n_nodes))
        write_json(input_path, config)
        generated.append(
            {
                "experiment_id": experiment_id,
                "N": n_nodes,
                "graph": chain_label(n_nodes),
                "combo": combo,
                "config": config,
                "input_path": input_path,
                "dag_path": dag_path,
            }
        )
    return generated


# ---------------------------------------------------------------------------
# Simulation execution and result collection
# ---------------------------------------------------------------------------


def find_latest_run_dir(experiment_name: str, arrival_rate: Any, log_dir: Path) -> Path:
    pattern = f"{experiment_name}_arr{arrival_rate}_*"
    def modified_time(path: Path) -> float:
        return path.stat().st_mtime

    candidates = sorted(log_dir.glob(pattern), key=modified_time)
    if not candidates:
        raise FileNotFoundError(f"No log directory found for {log_dir / pattern}")
    return candidates[-1]


def load_graph_rows(run_dir: Path) -> pd.DataFrame:
    metrics_path = run_dir / "all_runs_metrics.csv"
    if metrics_path.exists():
        df = pd.read_csv(metrics_path)
        if "level" in df.columns:
            return df[df["level"] == "graph"].copy()
        return df.copy()

    summary_path = run_dir / "all_runs_summary.csv"
    if summary_path.exists():
        return pd.read_csv(summary_path)

    aggregated_path = run_dir / "aggregated_results.json"
    if aggregated_path.exists():
        with aggregated_path.open() as f:
            aggregated = json.load(f)
        rows = []
        for result in aggregated.get("runs", []):
            rows.append({key: value for key, value in result.items() if key != "per_node"})
        return pd.DataFrame(rows)

    raise FileNotFoundError(f"No simulator result file found in {run_dir}")


def run_one_experiment(
    python: Path,
    generated: dict[str, Any],
    output_dir: Path,
    continue_on_error: bool,
) -> pd.DataFrame:
    stdout_dir = output_dir / "logs" / "stdout"
    stdout_dir.mkdir(parents=True, exist_ok=True)
    stdout_path = stdout_dir / f"{generated['experiment_id']}.log"
    config = generated["config"]

    cmd = [
        str(python),
        str(SIMULATE),
        "--input",
        str(generated["input_path"]),
        "--dag",
        str(generated["dag_path"]),
    ]

    print(f"Running {generated['experiment_id']} ...", flush=True)
    try:
        with stdout_path.open("w") as stdout_file:
            subprocess.run(
                cmd,
                cwd=ROOT,
                check=True,
                stdout=stdout_file,
                stderr=subprocess.STDOUT,
            )
        run_dir = find_latest_run_dir(
            config["experiment_name"],
            config["arrival_rate"],
            Path(config["log_dir"]),
        )
        df = load_graph_rows(run_dir)
        df["status"] = "ok"
        df["error"] = ""
        df["run_dir"] = str(run_dir)
    except Exception as exc:
        if not continue_on_error:
            raise
        df = pd.DataFrame([{"status": "failed", "error": str(exc), "run_dir": ""}])

    df["experiment_id"] = generated["experiment_id"]
    df["experiment_name"] = config["experiment_name"]
    df["N"] = generated["N"]
    df["graph"] = generated["graph"]
    df["config_path"] = str(generated["input_path"])
    df["dag_path"] = str(generated["dag_path"])
    df["stdout_log"] = str(stdout_path)
    for key, value in generated["combo"].items():
        df[key] = json.dumps(value) if isinstance(value, (dict, list)) else value
    return df


def run_experiments(
    generated: list[dict[str, Any]],
    output_dir: Path,
    continue_on_error: bool,
) -> pd.DataFrame:
    python = PYTHON if PYTHON.exists() else Path(sys.executable)
    frames = [
        run_one_experiment(python, item, output_dir, continue_on_error)
        for item in generated
    ]
    return pd.concat(frames, ignore_index=True) if frames else pd.DataFrame()


# ---------------------------------------------------------------------------
# Plotting
# ---------------------------------------------------------------------------


def available_metric_columns(df: pd.DataFrame) -> list[str]:
    metrics = []
    for column in df.columns:
        if column in METADATA_COLUMNS:
            continue
        if column.endswith("_path") or column.endswith("_log"):
            continue
        numeric = pd.to_numeric(df[column], errors="coerce")
        if numeric.notna().any():
            metrics.append(column)
    return metrics


def resolve_metrics(requested_metrics: list[str], available_metrics: list[str]) -> list[str]:
    resolved = []
    missing = []
    for metric in requested_metrics:
        if metric in available_metrics:
            resolved.append(metric)
            continue
        candidates = METRIC_ALIASES.get(metric, [])
        match = next((candidate for candidate in candidates if candidate in available_metrics), None)
        if match:
            resolved.append(match)
        else:
            missing.append(metric)

    if missing:
        available = ", ".join(sorted(available_metrics))
        raise ValueError(
            "Requested z_metrics are not available: "
            f"{', '.join(missing)}. Available numeric metrics: {available}"
        )
    return list(dict.fromkeys(resolved))


def varied_parameters(sweeps: dict[str, list[Any]], plot_by: list[str] | None) -> list[str]:
    if plot_by is not None:
        return [SWEEP_ALIASES.get(name, name) for name in plot_by if SWEEP_ALIASES.get(name, name) != "N"]
    return [
        name
        for name, values in sweeps.items()
        if name != "N" and len({json.dumps(value, sort_keys=True) for value in values}) > 1
    ]


def numeric_column(df: pd.DataFrame, column: str) -> pd.Series:
    return pd.to_numeric(df[column], errors="coerce")


def is_numeric_parameter(df: pd.DataFrame, column: str) -> bool:
    return numeric_column(df, column).notna().all()


def sorted_unique(values: pd.Series, numeric: bool) -> list[Any]:
    clean = values.dropna().unique().tolist()
    if numeric:
        return sorted(clean, key=float)
    return sorted(clean, key=str)


def context_groups(df: pd.DataFrame, param: str, sweep_params: list[str]):
    other_params = [name for name in sweep_params if name not in {"N", param}]
    other_params = [name for name in other_params if name in df.columns and df[name].nunique(dropna=False) > 1]
    if not other_params:
        yield "", df
        return
    for values, group in df.groupby(other_params, dropna=False):
        if not isinstance(values, tuple):
            values = (values,)
        suffix_bits = [
            f"{name}-{compact_value(value)}"
            for name, value in zip(other_params, values)
        ]
        yield "__" + "__".join(suffix_bits), group


def plot_2d(df: pd.DataFrame, metric: str, param: str, output_dir: Path, suffix: str = "") -> Path | None:
    plot_df = df[["N", param, metric]].copy()
    plot_df["N"] = numeric_column(plot_df, "N")
    plot_df[metric] = numeric_column(plot_df, metric)
    plot_df = plot_df.dropna(subset=["N", param, metric])
    if plot_df.empty:
        return None

    numeric_param = is_numeric_parameter(plot_df, param)
    plot_df = (
        plot_df.groupby(["N", param], dropna=False, as_index=False)[metric]
        .mean()
        .sort_values(["N", param])
    )

    fig, ax = plt.subplots(figsize=(9, 5.5))
    for param_value in sorted_unique(plot_df[param], numeric_param):
        curve = plot_df[plot_df[param] == param_value].sort_values("N")
        ax.plot(curve["N"], curve[metric], marker="o", linewidth=1.8, label=f"{param}={param_value}")

    ax.set_xlabel("N")
    ax.set_ylabel(metric)
    ax.grid(True, alpha=0.3)
    ax.legend(title=param, fontsize=8)
    fig.tight_layout()

    output_dir.mkdir(parents=True, exist_ok=True)
    path = output_dir / f"plot_2d_{metric}_vs_N_by_{param}{suffix}.png"
    fig.savefig(path, dpi=170)
    plt.close(fig)
    return path


def plot_3d(df: pd.DataFrame, metric: str, param: str, output_dir: Path, suffix: str = "") -> Path | None:
    plot_df = df[["N", param, metric]].copy()
    plot_df["N"] = numeric_column(plot_df, "N")
    plot_df[metric] = numeric_column(plot_df, metric)
    plot_df = plot_df.dropna(subset=["N", param, metric])
    if plot_df.empty:
        return None

    numeric_param = is_numeric_parameter(plot_df, param)
    plot_df = plot_df.groupby(["N", param], dropna=False, as_index=False)[metric].mean()
    param_values = sorted_unique(plot_df[param], numeric_param)
    param_positions = {value: idx for idx, value in enumerate(param_values)}
    if numeric_param:
        plot_df["_param_x"] = numeric_column(plot_df, param)
    else:
        plot_df["_param_x"] = plot_df[param].map(param_positions)

    fig = plt.figure(figsize=(9, 7))
    ax = fig.add_subplot(111, projection="3d")

    pivot = plot_df.pivot(index="N", columns="_param_x", values=metric).sort_index()
    use_surface = pivot.shape[0] >= 2 and pivot.shape[1] >= 2 and not pivot.isna().all().all()
    if use_surface:
        x_values = pivot.columns.to_list()
        y_values = pivot.index.to_list()
        x_grid, y_grid = np.meshgrid(x_values, y_values)
        ax.plot_surface(x_grid, y_grid, pivot.to_numpy(), cmap="viridis", alpha=0.82, edgecolor="none")
        ax.scatter(plot_df["_param_x"], plot_df["N"], plot_df[metric], color="black", s=22)
    else:
        ax.scatter(plot_df["_param_x"], plot_df["N"], plot_df[metric], s=36)

    ax.set_xlabel(param)
    ax.set_ylabel("N")
    ax.set_zlabel(metric)
    if not numeric_param:
        ax.set_xticks(list(param_positions.values()))
        ax.set_xticklabels([str(value) for value in param_values], rotation=25, ha="right")
    fig.tight_layout()

    output_dir.mkdir(parents=True, exist_ok=True)
    path = output_dir / f"plot_3d_{metric}_N_{param}{suffix}.png"
    fig.savefig(path, dpi=170)
    plt.close(fig)
    return path


def plot_all(
    results: pd.DataFrame,
    z_metrics: list[str],
    plot_params: list[str],
    sweep_params: list[str],
    output_dir: Path,
) -> list[Path]:
    figures: list[Path] = []
    ok = results[results.get("status", "ok") == "ok"].copy()
    for metric in z_metrics:
        for param in plot_params:
            if param not in ok.columns:
                print(f"Skipping plots for unknown sweep parameter: {param}")
                continue
            for suffix, group in context_groups(ok, param, sweep_params):
                fig2d = plot_2d(group, metric, param, output_dir / "plots" / "2d", suffix)
                fig3d = plot_3d(group, metric, param, output_dir / "plots" / "3d", suffix)
                figures.extend(path for path in [fig2d, fig3d] if path is not None)
    return figures


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate Cartesian-product sanity sweeps and plot graph-level simulator metrics."
    )
    parser.add_argument(
        "--config",
        type=Path,
        help=(
            "Optional JSON override with keys: base_config, node_defaults, "
            "sweeps, z_metrics, plot_by_parameters."
        ),
    )
    parser.add_argument(
        "--output-prefix",
        default="sanitycheck_sweep",
        help="Output directory for configs, logs, results.csv, and plots.",
    )
    parser.add_argument(
        "--generate-only",
        action="store_true",
        help="Write config/DAG files but do not call simulate.py.",
    )
    parser.add_argument(
        "--stop-on-error",
        action="store_true",
        help="Stop at the first failed simulator run instead of recording a failed row.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    override = load_runner_config(args.config)

    base_config = deep_update(BASE_SIMULATION_CONFIG, override.get("base_config", {}))
    node_defaults = deep_update(NODE_DEFAULTS, override.get("node_defaults", {}))
    sweeps = normalize_sweeps(override.get("sweeps", SWEEPS))
    z_metric_requests = override.get("z_metrics", Z_METRICS)
    plot_by = override.get("plot_by_parameters", PLOT_BY_PARAMETERS)

    output_dir = output_root(args.output_prefix)
    combos = cartesian_product(sweeps)
    generated = generate_experiment_files(combos, base_config, node_defaults, output_dir)
    manifest = pd.DataFrame(
        {
            **{"experiment_id": item["experiment_id"], "N": item["N"]},
            **item["combo"],
            "config_path": str(item["input_path"]),
            "dag_path": str(item["dag_path"]),
        }
        for item in generated
    )
    output_dir.mkdir(parents=True, exist_ok=True)
    manifest.to_csv(output_dir / "generated_configs.csv", index=False)

    print(f"Generated {len(generated)} experiment configurations in {output_dir / 'configs'}")
    if args.generate_only:
        print("Generate-only mode: not running simulate.py.")
        return

    results = run_experiments(generated, output_dir, continue_on_error=not args.stop_on_error)
    results_csv = output_dir / "results.csv"
    results.to_csv(results_csv, index=False)

    if results.empty or not (results.get("status", "failed") == "ok").any():
        print(f"No completed simulator runs. Wrote failure table to {results_csv}")
        return

    available_metrics = available_metric_columns(results[results["status"] == "ok"])
    z_metrics = resolve_metrics(z_metric_requests, available_metrics)
    plot_params = varied_parameters(sweeps, plot_by)
    figures = plot_all(results, z_metrics, plot_params, list(sweeps), output_dir)

    print("\nDone.")
    print(f"Results CSV: {results_csv}")
    print(f"Generated configs CSV: {output_dir / 'generated_configs.csv'}")
    print(f"Plots: {output_dir / 'plots'}")
    print(f"Metrics plotted: {', '.join(z_metrics)}")
    print(f"Input axes plotted: {', '.join(plot_params) if plot_params else '(none)'}")
    print(f"Figures written: {len(figures)}")


if __name__ == "__main__":
    main()
